version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: advpro-2024-mod5
    environment:
      POSTGRES_DB: advpro-2024
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: